
version: "3.7"
services:
  web:
    platform: linux/amd64
    command: npm run production
    container_name: next-docker-production
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next